using System.ComponentModel;
namespace ViVeUI.Windows;
public sealed class Locale : INotifyPropertyChanged
{
    public event PropertyChangedEventHandler? PropertyChanged;
    public string Language { get; private set; } = "en";
    public void Set(string language) { Language = language; PropertyChanged?.Invoke(this, new("Item[]")); }
    public string this[string key] => Text.TryGetValue(key, out var row) ? row[Language == "zh" ? 1 : Language == "es" ? 2 : 0] : key;
    public static readonly Dictionary<string, string[]> Text = new()
    {
        ["Explore"] = ["Explore", "探索", "Explorar"], ["Changes"] = ["My changes", "我的更改", "Mis cambios"], ["Updates"] = ["Updates", "更新", "Actualizaciones"], ["Settings"] = ["Settings & about", "设置与关于", "Ajustes y detalles"],
        ["Tagline"] = ["Windows, thoughtfully explored.", "从容探索 Windows。", "Explora Windows con criterio."],
        ["ExploreTitle"] = ["A little more possibility.", "探索更多可能。", "Un mundo de posibilidades."],
        ["ExploreSubtitle"] = ["Explore the catalog. Understand the unknowns. Make one considered change.", "浏览目录，了解未知，谨慎尝试每一次更改。", "Explora el catálogo. Comprende lo desconocido. Revisa cada cambio."],
        ["Coverage"] = ["17,000 catalog IDs · upstream snapshot · March 2025", "17,000 个目录 ID · 上游快照 · 2025 年 3 月", "17.000 ID · catálogo de origen · marzo de 2025"],
        ["CoverageNote"] = ["Catalog presence does not establish support on your Windows build. Missing observations do not mean disabled.", "目录收录不代表你的 Windows 版本支持此功能。未观察到不等于已禁用。", "Estar en el catálogo no garantiza compatibilidad. Sin observaciones no significa desactivado."],
        ["Search"] = ["Search names or feature IDs", "搜索名称或功能 ID", "Buscar nombres o ID"], ["All"] = ["All features", "全部功能", "Todas las funciones"],
        ["Explorer"] = ["File Explorer", "文件资源管理器", "Explorador de archivos"], ["Widgets"] = ["Widgets", "小组件", "Widgets"], ["System"] = ["System tools", "系统工具", "Herramientas del sistema"], ["Catalog"] = ["Unclassified catalog", "未分类目录", "Catálogo sin clasificar"],
        ["AddId"] = ["Inspect ID", "查看 ID", "Inspeccionar ID"], ["Refresh"] = ["Refresh observations", "刷新观测", "Actualizar observaciones"],
        ["Detail"] = ["FEATURE DETAILS", "功能详情", "DETALLES"], ["Schematic"] = ["Original conceptual illustration · not a Windows screenshot", "原创概念示意图 · 非 Windows 截图", "Ilustración conceptual original · no es una captura de Windows"],
        ["NoPreview"] = ["No verified visual preview", "暂无经验证的外观预览", "Sin vista previa verificada"],
        ["UnknownDescription"] = ["The upstream name is a technical identifier. Behavior, prerequisites, dependencies and build compatibility are unverified. This app does not infer them from the name.", "上游名称为技术标识符。行为、前提条件、依赖关系及版本兼容性均未经验证。本应用不会根据名称推断这些信息。", "El nombre de origen es un identificador técnico. El comportamiento, requisitos y compatibilidad no están verificados; no se deducen del nombre."],
        ["Historical"] = ["Historical example only. The illustration describes a category, not the appearance or availability of this feature on your PC.", "仅供历史参考。示意图表示类别，不代表此功能在你电脑上的外观或可用性。", "Ejemplo histórico. La ilustración representa una categoría, no la apariencia ni disponibilidad en tu PC."],
        ["Observed"] = ["Observed runtime configuration", "观测到的运行时配置", "Configuración de ejecución observada"], ["NotObserved"] = ["Not observed / applicability unknown", "未观察到 / 适用性未知", "Sin observaciones / compatibilidad desconocida"],
        ["UserOverride"] = ["User boot override · priority 8", "用户启动覆盖 · 优先级 8", "Anulación de arranque · prioridad 8"], ["Default"] = ["Windows default", "Windows 默认", "Predeterminado de Windows"], ["Enabled"] = ["Enable", "启用", "Activar"], ["Disabled"] = ["Disable", "禁用", "Desactivar"],
        ["DefaultHelp"] = ["Default removes this user override; it does not mean disabled. Other Windows priorities may still win. A restart is required after changes.", "默认将移除此用户覆盖，不等于禁用。其他 Windows 优先级仍可能生效。更改后需要重启。", "Predeterminado elimina esta anulación; no significa desactivado. Otras prioridades pueden prevalecer. Los cambios requieren reiniciar."],
        ["Stage"] = ["Add to review", "加入审核", "Añadir a revisión"], ["Source"] = ["Open pinned source", "打开固定版本来源", "Abrir fuente fijada"], ["Review"] = ["Review changes", "审核更改", "Revisar cambios"], ["Staged"] = ["staged changes", "项待审核更改", "cambios pendientes"],
        ["NoChanges"] = ["Your next change starts with a review.", "每一次更改都从审核开始。", "Cada cambio comienza con una revisión."],
        ["ReviewTitle"] = ["One final look.", "最后确认。", "Una última revisión."], ["ReviewHelp"] = ["These changes affect only the listed user boot overrides. Experiments can make Windows unstable. Save your work and arrange a recovery path. Apply one experiment at a time when possible.", "仅修改以下用户启动覆盖。实验性功能可能导致 Windows 不稳定。请保存工作并准备恢复方案。建议每次只尝试一个实验。", "Solo se modifican las anulaciones indicadas. Los experimentos pueden afectar la estabilidad. Guarda tu trabajo y prepara la recuperación. Prueba un experimento cada vez."],
        ["Apply"] = ["Apply with administrator approval", "经管理员批准后应用", "Aplicar con autorización de administrador"], ["Clear"] = ["Clear review", "清空待审核", "Vaciar revisión"], ["Before"] = ["Before", "更改前", "Antes"], ["After"] = ["After", "更改后", "Después"],
        ["History"] = ["Change history", "更改历史", "Historial de cambios"], ["Undo"] = ["Review restore of selected entry", "审核恢复所选记录", "Revisar restauración de la entrada"], ["HistoryHelp"] = ["Restore uses the recorded snapshot, not a global reset. Conflicts stop undo. Pending entries can be reconciled against the current state; they are not proof of success.", "恢复使用已记录的快照，而非全局重置。冲突会阻止撤销。待定记录可与当前状态核对，但不代表操作成功。", "Se restaura la instantánea guardada. Los conflictos bloquean la operación. Las entradas pendientes no demuestran que se aplicó un cambio."],
        ["UpdateTitle"] = ["Stay curious. Stay current.", "保持好奇，及时更新。", "Sigue explorando. Mantente al día."], ["UpdateHelp"] = ["Updates come only from BlakeLiAFK/ViVeUI releases on GitHub. Packages are checked against GitHub's SHA-256 asset digest. Downloads never install or launch themselves.", "仅从 GitHub 的 BlakeLiAFK/ViVeUI 发布下载更新，并校验 GitHub 提供的 SHA-256 摘要。下载后不会自动安装或运行。", "Las actualizaciones proceden de BlakeLiAFK/ViVeUI en GitHub. Se verifica el resumen SHA-256. Nunca se instalan ni ejecutan automáticamente."],
        ["Check"] = ["Check for updates", "检查更新", "Buscar actualizaciones"], ["Download"] = ["Download verified package", "下载并验证安装包", "Descargar paquete verificado"], ["OpenDownloads"] = ["Open download folder", "打开下载目录", "Abrir carpeta de descargas"],
        ["AutoCheck"] = ["Check for updates when this app opens", "打开应用时检查更新", "Buscar actualizaciones al abrir"], ["AutoDownload"] = ["Automatically download verified updates after a successful check", "检查成功后自动下载并验证更新", "Descargar y verificar actualizaciones tras comprobarlas"],
        ["Idle"] = ["Not checked yet", "尚未检查", "Sin comprobar"], ["Checking"] = ["Checking trusted source…", "正在检查可信来源…", "Comprobando fuente de confianza…"], ["Current"] = ["You have the latest published version", "已是最新发布版本", "Tienes la última versión publicada"], ["Available"] = ["A newer version is available", "有新版本可用", "Hay una nueva versión"], ["Downloading"] = ["Downloading and verifying…", "正在下载并验证…", "Descargando y verificando…"], ["Ready"] = ["Verified package ready · open folder to install manually", "安装包已验证 · 打开目录手动安装", "Paquete verificado · abre la carpeta para instalarlo"], ["Failed"] = ["Check or download failed · see details below", "检查或下载失败 · 详情见下方", "Error de comprobación o descarga · consulta los detalles"],
        ["SettingsTitle"] = ["Make it feel like home.", "用你熟悉的方式。", "Siéntete como en casa."], ["Language"] = ["Interface language", "界面语言", "Idioma de la interfaz"], ["Scale"] = ["Text and interface scale", "文字与界面缩放", "Escala de texto e interfaz"], ["About"] = ["Built on ViVe · GPL-3.0-or-later", "基于 ViVe · GPL-3.0-or-later", "Basado en ViVe · GPL-3.0-or-later"],
        ["AboutHelp"] = ["ViVeUI 0.1.0. Full pinned upstream source, licenses, original artwork and build instructions ship with the source package. No telemetry. Browsing is offline and does not require elevation.", "ViVeUI 0.1.0。源码包包含固定上游源码、许可证、原创图像和构建说明。无遥测。可离线浏览，无需提升权限。", "ViVeUI 0.1.0. El paquete fuente incluye el código original fijado, licencias, ilustraciones e instrucciones. Sin telemetría. Explora sin conexión ni elevación."],
        ["Demo"] = ["DEMO · simulated changes only", "演示 · 仅模拟更改", "DEMO · solo cambios simulados"], ["Local"] = ["LOCAL · browsing without elevation", "本地 · 无需提权即可浏览", "LOCAL · exploración sin elevación"], ["Error"] = ["Action could not be completed", "无法完成操作", "No se pudo completar la acción"], ["Restart"] = ["Verified changes saved. Restart Windows when you are ready.", "已验证并保存更改。请在准备好后重启 Windows。", "Cambios verificados y guardados. Reinicia Windows cuando quieras."],
        ["Empty"] = ["No matching features. Try a shorter name or inspect a numeric ID.", "没有匹配的功能。请尝试更短的名称或查看数字 ID。", "Sin coincidencias. Prueba otro nombre o inspecciona un ID."], ["UnknownId"] = ["Unknown ID (not in pinned catalog)", "未知 ID（未收录于固定目录）", "ID desconocido (fuera del catálogo)"], ["InvalidId"] = ["Enter a non-zero 32-bit feature ID in the search field.", "请在搜索框中输入非零的 32 位功能 ID。", "Introduce un ID de 32 bits distinto de cero en la búsqueda."], ["Unchanged"] = ["This matches the current override. Nothing was staged.", "与当前覆盖相同，未加入待审核列表。", "Coincide con la anulación actual. No se añadió ningún cambio."], ["Applied"] = ["Applied and verified", "已应用并验证", "Aplicado y verificado"], ["Pending"] = ["Pending / outcome uncertain", "待定 / 结果不确定", "Pendiente / resultado incierto"], ["Partial"] = ["Partial or failed · inspect results", "部分成功或失败 · 请查看结果", "Parcial o fallido · revisa los resultados"],
        ["HistoricalSource"] = ["Read historical context", "阅读历史背景", "Leer contexto histórico"], ["ObservationError"] = ["Observations unavailable", "观测不可用", "Observaciones no disponibles"], ["Diagnostics"] = ["Technical details (original system text)", "技术详情（系统原文）", "Detalles técnicos (texto original)"], ["SafetyAck"] = ["I understand these are experimental changes and have reviewed the exact IDs and states.", "我了解这些是实验性更改，并已审核具体 ID 和状态。", "Entiendo que son cambios experimentales y he revisado los ID y estados."],
    };
}
